"""fixs_bag_second

Revision ID: 11c6842e6fa2
Revises: a175549eae05
Create Date: 2023-06-28 20:59:21.923555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11c6842e6fa2'
down_revision = 'a175549eae05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
