"""fixs_bag_second_4

Revision ID: 29dce0b353e3
Revises: bd5f8d1de86e
Create Date: 2023-06-28 21:22:12.905715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29dce0b353e3'
down_revision = 'bd5f8d1de86e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
