"""tru

Revision ID: 34c7a708e4d6
Revises: 0ed239aa5c96
Create Date: 2023-06-28 19:31:35.491565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34c7a708e4d6'
down_revision = '0ed239aa5c96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
