"""fixs_bag

Revision ID: a175549eae05
Revises: 34c7a708e4d6
Create Date: 2023-06-28 20:53:13.083127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a175549eae05'
down_revision = '34c7a708e4d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
