"""fixs_bag_second_3

Revision ID: bd5f8d1de86e
Revises: 11c6842e6fa2
Create Date: 2023-06-28 21:01:18.896404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd5f8d1de86e'
down_revision = '11c6842e6fa2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
